#   dockerize Build container
stages:
  - dockerize
  
dockerize:
  stage: dockerize
  image: docker
  only:
    - tags
  # Use Docker in Docker service, to build Docker in Docker
  services:
    - docker:dind
  script:
    # Login to Gitlab Docker registry using built-in variables
    - docker login
      -u "$CI_REGISTRY_USER"
      -p "$CI_REGISTRY_PASSWORD"
      $CI_REGISTRY
    # Build it! Name will be project_name:branch_name
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG .
    # Push freshly built image to Gitlab registry
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
